### ISSUE TITLE
Can this connector be used to connect local DB2 in iSeries?

### ISSUE THREAD

**Issue by cdjim** [strongloop/loopback-connector-db2iseries#32]
# Description/Steps to reproduce
Hi there,

This connector is so great, supporting iSeries DB2 datasource in Loopback. But I am not sure whether it can be used to connect DB2 locally, if my app is running in iSeries. Can someone give me some advices on how this works?

# Link to reproduction sandbox

# Expected result

# Additional information

I am going to build my app in iSeries by leveraging Loopback framework. It will connect to local DB2 (file library). If such connector is not designed for connecting local datasource in iSeries, do you know, by any chance that how I can integrate the connector installed in iSeries with loopback? 

Appreciate if anyone can shed some lights.

**Comment by dhmlau** [comment]
@cdjim, I haven't worked with iSeries before, so trying to understand what you're trying to do. 
- The database connection information is captured in datasources.json.  If you change the location of the database, you can edit that file.
- The connector is installed within the LoopBack application, so there's no need for integration.

**Comment by cdjim** [comment]
@dhmlau Diana, thanks for your feedback. 

Maybe I explain more specifically. We are going to develop an nodejs app hosted in iSeries. It will connect to the local DB2 in the same machine. 

LoopBack is nice. But we have the last puzzle to be fixed, before we can leverage LoopBack to develop nodejs codes in iSeries. That is the DB2 connection. 

This is why I raised the question. Any helps is appreciated. 

FYI. The nodejs package installed in iSeries comes with ‘DB2 for i access library’ APIs, which can be used connect to local DB2 database. Not sure if we have to build a LoopBack ds connector by ourselves. :(

**Comment by dhmlau** [comment]
@cdjim , thanks for your explanation.
@qpresley , do you have any insights on this?  Thanks.

**Comment by qpresley** [comment]
@cdjim We haven't tried running the LB app on iSeries so that is a bit tough to say.  The Node.js code should work regardless of platform however this connector relies on the DB2 UDB (Unix/Windows) client code which likely will not work on iSeries.  My expectation is that it will not work unfortunately.

**Comment by cdjim** [comment]
@qpresley thanks for the advice. Will close the issue.

**Comment by ThePrez** [comment]
@cdjim, not sure if you're still interested in this, but the new `loopback-connector-ibmi` can connect to local Db2 on IBM i.

**Comment by cdjim** [comment]
> @cdjim, not sure if you're still interested in this, but the new `loopback-connector-ibmi` can connect to local Db2 on IBM i.

@ThePrez, thank you so much for letting me know. Will definitely try on IBM i. 
BTW, may I know whether it's production ready version, or just an alpha/beta version?
