### ISSUE TITLE
[Discussion] Should we use loopback-connector-ibmi instead?

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-db2iseries#35]
Now that we have the [loopback-connector-ibmi connector](https://github.com/strongloop/loopback-connector-ibmi), does it mean we should deprecate this (loopback-connector-db2iseries) connector? 

IIRC, there are a few advantages of using `loopback-connector-ibmi`, see https://github.com/strongloop-internal/scrum-apex/issues/415. 

cc @raymondfeng @bajtos @strongloop/ibmi-maintainers

**Comment by ThePrez** [comment]
I would be in favor, but we should involve the `loopback-connector-db2iseries` maintainers to explain the merits of their package. Maybe it has some benefit that would warrant its coexistence

**Comment by ThePrez** [comment]
I vote yes. 

The IBM i connector has several advantages. Plus, this project hasn't had any functional updates in several years and hasn't been updated to use the N-API. On top of that, iSeries was replaced by POWER Systems over a decade ago.

**Comment by dhmlau** [comment]
@qpresley, since you're the original author of this module, what's your thought on this?

**Comment by dhmlau** [comment]
I've talked to @qpresley. 

1. He mentioned that if the new connector (loopback-connector-ibmi) can run on Windows/Unix machine and connect to a DB2 instance on IBM i, this connector can be deprecated.  

   @ThePrez, could you please comment on this? 

2. Since we might still have customers using it, if we are to deprecate this connector, we might need to put out a notice including docs to move to the new connector.

**Comment by ThePrez** [comment]
The new `loopback-connector-ibmi` can run on Windows and Linux, but not on other Unixes (so no AIX, HP-UX, Solaris, etc). If this connector can run on more platforms, then maybe that's a good reason for it to stick around. Thoughts?

**Comment by kadler** [comment]
Do we _have_ any IBM i customers that connect from any of these platforms? I suspect no.

**Comment by qpresley** [comment]
We did have one but I don't know if they are still using it.  They were the reason we wrote the db2iseries version in the first place.

**Comment by ThePrez** [comment]
Thanks, @qpresley. What platform was that client using? AIX?

**Comment by qpresley** [comment]
That I don't recall.  Its been between 2 and 3 years since I worked with them and can't recall what platoform they were working from.

**Comment by ThePrez** [comment]
> That I don't recall. Its been between 2 and 3 years since I worked with them and can't recall what platoform they were working from.

Relatable! 😄 

Regardless, I would think customers connecting from platforms other than IBM i, Linux, Windows, or Mac (available soon with new connector) would be pretty rare.

Maybe we can deprecate it and in the docs have some guidance to let us know if they're connecting from a platform for which the new connector doesn't work. If anyone raises their proverbial hand, we can re-assess the best plan of action.

**Comment by qpresley** [comment]
Sounds reasonable to me.

**Comment by dhmlau** [comment]
I still see download activities in this module: https://npm-stat.com/charts.html?package=loopback-connector-db2iseries, not sure if it's coming from @ThePrez and team. 

**At the connector level:**
>  in the docs have some guidance to let us know if they're connecting from a platform for which the new connector doesn't work

+1

We could put it in a way that loopback-connector-ibmi is the recommended connector over loopback-connector-db2iseries because ... (here are the reasons)...  In that case, whoever building a new application should use the new one instead.  There might be some best practices in deprecating a module in the open source world, and I'd like to get opinions from @bajtos and/or @raymondfeng on it too. 

**For the datasource CLI**, 
I'd like to propose:
- no change in the datasource CLI in LB3. LB3 will go EOL at the end of 2020 anyway
- remove the `loopback-connector-db2iseries` option so that it only has `loopback-connector-ibmi` for db2 i related connectors. It's not likely we have IBM i users using the old connector in LB4. Like @ThePrez said, if someone raise any issue, we can always re-assess.

**Comment by ThePrez** [comment]
> I still see download activities in this module: https://npm-stat.com/charts.html?package=loopback-connector-db2iseries, not sure if it's coming from @ThePrez and team.

We haven't been downloading it, but we have gotten numerous contacts from people asking about failures due to a lack of licensing files. This was actually a motivator for the `loopback-connector-ibmi` project, since we saw a demand for loopback but a success rate we perceived as low, since the average IBM i client does not have the licensing in place for the db2iseries flavor to work.

**Comment by bajtos** [comment]
The proposal(s) described above looks reasonable to me.

> There might be some best practices in deprecating a module in the open source world

I see two options:

1. A soft deprecation, where we add a prominent notice to our documentation (especially the README file) explaining that the module is deprecated and users should switch to `loopback-connector-ibmi`.
2. A hard deprecation using [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) command. `npm install` will print a warning for packages deprecated such way. This mechanism is usually used for versions that are known to contain security vulnerabilities. We (module authors) are expected to provide the message that will be printed by `npm install`.

I think it's better to use soft deprecation first, at least until the new connector supports MacOS too.

**Comment by ThePrez** [comment]
If we go with soft deprecation, should we also consider renaming the connector to something like `IBM Db2 for iSeries (deprecated)`? 

I like a hard deprecation because it's more likely to make a user "speak up" if they see an issue with the deprecation (maybe), but I'm 100% good with either approach.

**Comment by dhmlau** [comment]
Thanks @bajtos @ThePrez. 
I prefer the soft deprecation as the first step, though good with either way. :) 

> If we go with soft deprecation, should we also consider renaming the connector to something like IBM Db2 for iSeries (deprecated)?

+1

@ThePrez, do you think you can make the corresponding changes? Thanks.

**Comment by ThePrez** [comment]
I'll ready a PR that adds the following for LB3: 
- Change of name to add "(deprecated)"
- Decumentation suggesting the new module for IBM i
No changes beyond that, which I think is aligned with @dhmlau's suggestion to not change the CLI for LB3. 

Since this module is no listed in the available connectors for LB4, I vote we just leave it out. There is some doc cleanup in LB4 that I can be done. I would propose doing that as part of landing the 'ibmi' flavor in LB4 (which I think is coming soon)

**Comment by kadler** [comment]
Can this be closed out? Seems like all the changes were merged or am I missing something?

**Comment by dhmlau** [comment]
sure. I think it's done. Thanks.
